services:
  - type: web
    name: qa-generator
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      python -m pip install --upgrade pip
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        sync: false  # This means you'll need to set this value in the Render dashboard 
    plan: free
    memory: 512MB 